export const QuestionsInfo = [
  {
    question: 'What is the value of x if 3x + 5 = 20?',
    options: ['5', '15', '10', '3'],
    correctAnswer: '5',
    topicTag: 'algebra',
    difficultyLevel: 'medium',
  },
  {
    question: 'What is the area of a triangle with base 6 cm and height 4 cm?',
    options: ['24 cm²', '10 cm²', '8 cm²', '12 cm²'],
    correctAnswer: '12 cm²',
    topicTag: 'geometry',
    difficultyLevel: 'easy',
  },
  {
    question: 'If the mean of 5 numbers is 20, what is their total sum?',
    options: ['50', '25', '100', '200'],
    correctAnswer: '100',
    topicTag: 'data_handling',
    difficultyLevel: 'medium',
  },
  {
    question: 'What is 7/8 expressed as a decimal?',
    options: ['0.78', '0.87', '0.85', '0.875'],
    correctAnswer: '0.875',
    topicTag: 'fractions_and_decimals',
    difficultyLevel: 'easy',
  },
  {
    question: 'What is (-12) + 15?',
    options: ['27', '3', '-3', '-27'],
    correctAnswer: '3',
    topicTag: 'integers',
    difficultyLevel: 'easy',
  },
  {
    question: 'What is the volume of a cube with a side length of 5 cm?',
    options: ['25 cm³', '125 cm³', '15 cm³', '100 cm³'],
    correctAnswer: '125 cm³',
    topicTag: 'mensuration',
    difficultyLevel: 'medium',
  },
  {
    question: 'Find the LCM of 12 and 18.',
    options: ['24', '36', '72', '18'],
    correctAnswer: '36',
    topicTag: 'playing_with_numbers',
    difficultyLevel: 'medium',
  },
  {
    question: 'If 5 books cost $20, what is the cost of 8 books?',
    options: ['$40', '$28', '$32', '$50'],
    correctAnswer: '$32',
    topicTag: 'unitary_method',
    difficultyLevel: 'easy',
  },
  {
    question:
      'If the ratio of boys to girls in a class is 3:5 and there are 40 students, how many are boys?',
    options: ['25', '20', '30', '15'],
    correctAnswer: '15',
    topicTag: 'ratio_and_proportion',
    difficultyLevel: 'medium',
  },
  {
    question: 'What is the smallest whole number?',
    options: ['1', '0', '-1', '2'],
    correctAnswer: '0',
    topicTag: 'whole_numbers',
    difficultyLevel: 'easy',
  },
  {
    question: 'Simplify: 2x - 3 = 7.',
    options: ['5', '7', '10', '2'],
    correctAnswer: '5',
    topicTag: 'algebra',
    difficultyLevel: 'medium',
  },
  {
    question:
      'What is the perimeter of a rectangle with length 8 cm and width 3 cm?',
    options: ['24 cm', '26 cm', '30 cm', '22 cm'],
    correctAnswer: '22 cm',
    topicTag: 'geometry',
    difficultyLevel: 'medium',
  },
  {
    question:
      'Which of the following is a mode of the data set [2, 3, 2, 5, 7, 2, 4, 5, 5]?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '2',
    topicTag: 'data_handling',
    difficultyLevel: 'hard',
  },
  {
    question: 'Convert 3.25 to a fraction.',
    options: ['6/5', '13/4', '7/3', '8/5'],
    correctAnswer: '13/4',
    topicTag: 'fractions_and_decimals',
    difficultyLevel: 'medium',
  },
  {
    question: 'What is the product of (-8) × (-7)?',
    options: ['-56', '56', '-15', '15'],
    correctAnswer: '56',
    topicTag: 'integers',
    difficultyLevel: 'easy',
  },
  {
    question: 'The curved surface area of a cylinder is calculated using:',
    options: ['πr²h', '2πr²', '2πrh', 'πr²'],
    correctAnswer: '2πrh',
    topicTag: 'mensuration',
    difficultyLevel: 'medium',
  },
  {
    question: 'Find the HCF of 36 and 48.',
    options: ['6', '12', '18', '24'],
    correctAnswer: '12',
    topicTag: 'playing_with_numbers',
    difficultyLevel: 'hard',
  },
  {
    question: 'If 4 pens cost $12, what is the cost of 10 pens?',
    options: ['$25', '$20', '$28', '$30'],
    correctAnswer: '$30',
    topicTag: 'unitary_method',
    difficultyLevel: 'medium',
  },
  {
    question:
      'The ratio of red to blue marbles is 3:4. If there are 21 red marbles, how many blue marbles are there?',
    options: ['28', '25', '35', '30'],
    correctAnswer: '28',
    topicTag: 'ratio_and_proportion',
    difficultyLevel: 'hard',
  },
  {
    question: 'What is 9 × 1?',
    options: ['1', '9', '10', '0'],
    correctAnswer: '9',
    topicTag: 'whole_numbers',
    difficultyLevel: 'easy',
  },
]
